<?php

namespace App\Repository;

/**
 * LevelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LevelAlertRepository extends \Doctrine\ORM\EntityRepository
{

}